"""
DOER Platform - Document Drafting Agent

Generates legal documents using local LLM (Ollama/Llama) with templates.

DOCUMENT TYPES:
- Legal Notice
- Affidavit
- Settlement Agreement

FEATURES:
- Template-based generation
- Vernacular output (Hindi support)
- Caching to avoid regeneration
- Fallback to templates if LLM unavailable

PRODUCTION UPGRADES:
- Fine-tuned legal LLM
- Multi-language support
- PDF generation
- Digital signature integration
"""

import os
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional
from enum import Enum


class DocumentType(str, Enum):
    """Types of legal documents."""
    LEGAL_NOTICE = "legal_notice"
    AFFIDAVIT = "affidavit"
    SETTLEMENT_AGREEMENT = "settlement_agreement"
    PARTITION_DEED = "partition_deed"
    UNDERTAKING = "undertaking"


# Document templates (markdown format)
DOCUMENT_TEMPLATES: Dict[str, str] = {
    "legal_notice": """
# LEGAL NOTICE

**Date:** {date}
**Notice No.:** {notice_number}

**TO:**
{recipient_name}
{recipient_address}

**FROM:**
{sender_name}
Through their authorized representative
{representative_name}

## SUBJECT: {subject}

Dear Sir/Madam,

Under instructions and on behalf of my client, {sender_name}, I do hereby serve upon you this Legal Notice as under:

1. That my client is the lawful owner/possessor of the land bearing {land_details}.

2. {dispute_description}

3. That despite repeated requests, you have failed to {action_required}.

4. That your actions constitute {legal_violation} under the provisions of {relevant_law}.

**YOU ARE HEREBY CALLED UPON** to {demand} within **{response_days} days** from the receipt of this notice, failing which my client shall be constrained to initiate appropriate legal proceedings against you, at your risk, cost and consequences.

Please treat this notice as final.

**{sender_name}**
Through Advocate

---
*This is a computer-generated document prepared by DOER Platform*
""",

    "affidavit": """
# AFFIDAVIT

**IN THE MATTER OF:** {case_subject}
**CASE ID:** {case_id}

I, **{deponent_name}**, aged about {age} years, {occupation}, resident of {address}, do hereby solemnly affirm and state as follows:

1. That I am the {relationship} in the above matter and am competent to swear this affidavit.

2. That I have personal knowledge of the facts stated herein.

3. {statement_1}

4. {statement_2}

5. {statement_3}

6. That whatsoever stated above is true to my personal knowledge and belief and nothing material has been concealed therefrom.

**VERIFICATION**

I, {deponent_name}, do hereby verify that the contents of paragraphs 1 to 6 are true to my knowledge and belief and no part of it is false.

Verified at {location} on this {date}.

**DEPONENT**

---
*Prepared using DOER Platform*
""",

    "settlement_agreement": """
# SETTLEMENT AGREEMENT

**Agreement Date:** {date}
**Case Reference:** {case_id}
**Location:** {location}

## BETWEEN:

**FIRST PARTY:** {party_1_name}, {party_1_details}
(hereinafter referred to as "First Party")

**AND**

**SECOND PARTY:** {party_2_name}, {party_2_details}
(hereinafter referred to as "Second Party")

## WHEREAS:

A. The parties have been in dispute regarding {dispute_subject}.

B. The parties, through mediation facilitated by DOER Platform, have agreed to settle the dispute amicably.

## NOW THIS AGREEMENT WITNESSETH:

### 1. SETTLEMENT TERMS

{settlement_terms}

### 2. CONSIDERATION

{consideration_details}

### 3. TIMELINES

{timeline_details}

### 4. MUTUAL RELEASES

Both parties hereby release each other from all claims, demands, and causes of action arising from the dispute.

### 5. BINDING EFFECT

This Agreement shall be binding upon the parties and their respective heirs, successors, and assigns.

### 6. GOVERNING LAW

This Agreement shall be governed by the laws of India and the courts at {jurisdiction} shall have exclusive jurisdiction.

**IN WITNESS WHEREOF**, the parties have executed this Agreement on the date first written above.

---

**FIRST PARTY**                    **SECOND PARTY**

Signature: ____________          Signature: ____________

Name: {party_1_name}              Name: {party_2_name}

Date: ____________               Date: ____________

**WITNESSES:**

1. ________________________

2. ________________________

---
*Generated by DOER Platform | This is a legally binding document*
""",
}


class DocumentDraftingAgent:
    """
    Generates legal documents using templates and optional LLM enhancement.
    """
    
    def __init__(self, cache_dir: Optional[str] = None, use_llm: bool = True):
        """
        Initialize the document drafting agent.
        
        Args:
            cache_dir: Directory for caching generated documents
            use_llm: Whether to use LLM for enhanced generation
        """
        self.cache_dir = Path(cache_dir or Path(__file__).parent.parent.parent / "data" / "generated_docs")
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.use_llm = use_llm
        self._ollama_available = self._check_ollama()
    
    def _check_ollama(self) -> bool:
        """Check if Ollama is available for LLM generation."""
        try:
            import requests
            response = requests.get("http://localhost:11434/api/tags", timeout=2)
            return response.status_code == 200
        except Exception:
            return False
    
    def _get_cache_key(self, doc_type: str, params: Dict[str, Any]) -> str:
        """Generate cache key for document."""
        content = f"{doc_type}:{sorted(params.items())}"
        return hashlib.md5(content.encode()).hexdigest()
    
    def _get_cached_doc(self, cache_key: str) -> Optional[str]:
        """Get cached document if exists."""
        cache_path = self.cache_dir / f"{cache_key}.md"
        if cache_path.exists():
            return cache_path.read_text(encoding='utf-8')
        return None
    
    def _save_to_cache(self, cache_key: str, content: str) -> Path:
        """Save document to cache."""
        cache_path = self.cache_dir / f"{cache_key}.md"
        cache_path.write_text(content, encoding='utf-8')
        return cache_path
    
    async def generate_legal_notice(
        self,
        case_id: int,
        sender_name: str,
        recipient_name: str,
        recipient_address: str,
        land_details: str,
        dispute_description: str,
        action_required: str,
        demand: str,
        response_days: int = 15,
        representative_name: str = "DOER Platform Legal Team",
        use_cache: bool = True
    ) -> Dict[str, Any]:
        """
        Generate a legal notice document.
        """
        params = {
            "date": datetime.utcnow().strftime("%d %B %Y"),
            "notice_number": f"LN/{case_id}/{datetime.utcnow().strftime('%Y%m%d')}",
            "sender_name": sender_name,
            "recipient_name": recipient_name,
            "recipient_address": recipient_address,
            "representative_name": representative_name,
            "subject": f"Legal Notice for Land Dispute - Case #{case_id}",
            "land_details": land_details,
            "dispute_description": dispute_description,
            "action_required": action_required,
            "demand": demand,
            "response_days": response_days,
            "legal_violation": "trespass and encroachment",
            "relevant_law": "the Transfer of Property Act, 1882 and Indian Penal Code"
        }
        
        return await self._generate_document(
            DocumentType.LEGAL_NOTICE, 
            params, 
            case_id, 
            use_cache
        )
    
    async def generate_affidavit(
        self,
        case_id: int,
        deponent_name: str,
        age: int,
        occupation: str,
        address: str,
        relationship: str,
        statements: list,
        location: str = "New Delhi",
        use_cache: bool = True
    ) -> Dict[str, Any]:
        """
        Generate an affidavit document.
        """
        params = {
            "case_subject": f"Land Dispute Case #{case_id}",
            "case_id": case_id,
            "deponent_name": deponent_name,
            "age": age,
            "occupation": occupation,
            "address": address,
            "relationship": relationship,
            "statement_1": statements[0] if len(statements) > 0 else "Statement 1",
            "statement_2": statements[1] if len(statements) > 1 else "Statement 2",
            "statement_3": statements[2] if len(statements) > 2 else "Statement 3",
            "location": location,
            "date": datetime.utcnow().strftime("%d day of %B, %Y")
        }
        
        return await self._generate_document(
            DocumentType.AFFIDAVIT, 
            params, 
            case_id, 
            use_cache
        )
    
    async def generate_settlement_agreement(
        self,
        case_id: int,
        party_1_name: str,
        party_1_details: str,
        party_2_name: str,
        party_2_details: str,
        dispute_subject: str,
        settlement_terms: str,
        consideration_details: str,
        timeline_details: str,
        jurisdiction: str = "Delhi",
        use_cache: bool = True
    ) -> Dict[str, Any]:
        """
        Generate a settlement agreement document.
        """
        params = {
            "date": datetime.utcnow().strftime("%d %B %Y"),
            "case_id": case_id,
            "location": jurisdiction,
            "party_1_name": party_1_name,
            "party_1_details": party_1_details,
            "party_2_name": party_2_name,
            "party_2_details": party_2_details,
            "dispute_subject": dispute_subject,
            "settlement_terms": settlement_terms,
            "consideration_details": consideration_details,
            "timeline_details": timeline_details,
            "jurisdiction": jurisdiction
        }
        
        return await self._generate_document(
            DocumentType.SETTLEMENT_AGREEMENT, 
            params, 
            case_id, 
            use_cache
        )
    
    async def _generate_document(
        self,
        doc_type: DocumentType,
        params: Dict[str, Any],
        case_id: int,
        use_cache: bool
    ) -> Dict[str, Any]:
        """
        Generate a document from template.
        """
        cache_key = self._get_cache_key(doc_type.value, params)
        
        # Check cache
        if use_cache:
            cached = self._get_cached_doc(cache_key)
            if cached:
                return {
                    "success": True,
                    "document_type": doc_type.value,
                    "case_id": case_id,
                    "content": cached,
                    "cached": True,
                    "generated_at": datetime.utcnow().isoformat()
                }
        
        # Get template
        template = DOCUMENT_TEMPLATES.get(doc_type.value)
        if not template:
            return {
                "success": False,
                "error": f"Template not found for {doc_type.value}"
            }
        
        # Generate document by filling template
        try:
            content = template.format(**params)
        except KeyError as e:
            return {
                "success": False,
                "error": f"Missing parameter: {e}"
            }
        
        # Optionally enhance with LLM
        if self.use_llm and self._ollama_available:
            content = await self._enhance_with_llm(content, doc_type)
        
        # Save to cache
        cache_path = self._save_to_cache(cache_key, content)
        
        return {
            "success": True,
            "document_type": doc_type.value,
            "case_id": case_id,
            "content": content,
            "cached": False,
            "cache_path": str(cache_path),
            "generated_at": datetime.utcnow().isoformat()
        }
    
    async def _enhance_with_llm(self, content: str, doc_type: DocumentType) -> str:
        """
        Enhance document with LLM for better language.
        
        Optional enhancement - returns original if LLM fails.
        """
        try:
            import requests
            
            prompt = f"""You are a legal document assistant. Review and improve the following {doc_type.value.replace('_', ' ')} for legal accuracy and clarity. 
Keep the same structure but improve the language. Output only the improved document, nothing else.

{content}"""
            
            response = requests.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "llama3.2",
                    "prompt": prompt,
                    "stream": False
                },
                timeout=60
            )
            
            if response.status_code == 200:
                result = response.json()
                return result.get("response", content)
            
        except Exception as e:
            print(f"LLM enhancement failed: {e}")
        
        return content
    
    def list_generated_documents(self, case_id: Optional[int] = None) -> list:
        """List all generated documents."""
        docs = []
        for path in self.cache_dir.glob("*.md"):
            doc_info = {
                "filename": path.name,
                "path": str(path),
                "size": path.stat().st_size,
                "modified": datetime.fromtimestamp(path.stat().st_mtime).isoformat()
            }
            docs.append(doc_info)
        return docs


# Singleton instance
_agent: Optional[DocumentDraftingAgent] = None


def get_document_agent() -> DocumentDraftingAgent:
    """Get or create the document drafting agent instance."""
    global _agent
    if _agent is None:
        _agent = DocumentDraftingAgent()
    return _agent
